spring:
  profiles:
    active: local

---
spring:
  profiles: local

server:
  error:
    include-stacktrace: on-trace-param
    
#logging
logging:
  file: logs/local-logging-file.log
  level:
    root: INFO
    org:
      springframework:
        batch: DEBUG
  pattern:
    # console에 찍히는 로그 형식 정의
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    # console에서 로그는 위에 형식으로 찍히지만 파일로 씌여질 때 해당 패턴으로 찍는다. 
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# ScheduleConfiguration thread pool size setup
thread:
  pool:
    size: 4

# defaul schedule rate 5 second
schedule:
  market:
    cron: '*/60 * * * * *'
  ticker:
    cron: '*/5 * * * * *'
  
# upbit information
# upbit access key and secret key
upbit:
  api:
    url: https://api.upbit.com
    version: /v1
  access:
    key: <Your Upbit Access Key>
  secret:
    key: <Your Upbit Secret Key>

telegram:
  api:
    token: <Your Telegram Api Token>
  bot:
    name: <Your Telegram Bot Name>
  chat:
    id: <Your Telegram Bot Chat Id>
  